version: "3.7"

services:
  backend:
    build: ./backend
    container_name: dashboard-app-backend
    env_file:
      - ./.env
    volumes:
      - ./backend:/backend/

  frontend:
    build: ./frontend
    container_name: dashboard-app-frontend
    env_file:
      - ./.env

    volumes:
      - ./frontend:/frontend

  nginx:
    build: ./nginx
    container_name: dashboard-app-nginx
    env_file:
      - ./.env
    ports:
      - 8080:80
    depends_on:
      - frontend
      - backend
