name: build & test
on:
  pull_request:
    types: [opened, reopened]
jobs:
  build-and-test:
  runs-on: [statndard]
  steps:
    - name: setup cache
      id: cache-setup
      uses: actions/cache@v2
      with:
      path: |
        backend/node_modules
        key: ${{ runner.os }}-deps-${{ hashFiles('backend/package.json') }}
    - name: install backend dependecies
      if: steps.cache-setup.outputs.cache-hit != 'true'
      working-directory: backend
      run: npm install
    - name: build backend
      working-directory: backend
      run: npm run build
    - name: lint backend
      working-directory: backend
      run: npm run lint
    - name: test backend
      working-directory: backend
      run: npm run test
    - name: npm run e2e tests
      working-directory: backend
      run: npm run test:e2e
    - name: install frontend dependencies
      working-directory: frontend
      run: npm install
    - name: build frotnend
      working-directory: frontend
      run: npm run build
    - name: lint frontend
      working-directory: frontend
      run: npm run lint
